[package]
name = "connect_four"
version = "0.1.0"
authors = ["Daniel Lockhart <cortesoft@gmail.com>"]

[dependencies]
connect_four_engine = { path = "connect_four_engine" }
neural_net = { path = "neural_net" }

[workspace]
